name: Go CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Install dependencies
      run: go mod tidy
      
    - name: Run Go Vulnerability Scanner
      uses: debug-ing/go-vuln-scanner@v1.0.0

    - name: Build project
      run: go build zlang.go