---
name: ci
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - uses: debug-ing/go-vuln-scanner@v1.0.0
    - name: Build project
      run: make build